### ISSUE TITLE
Unit Test Fail (tests.testutils ImportError)

### ISSUE THREAD

**Issue by jraysajulga** [caleb-easterly/metaquantome#2]
python -m unittest discover tests > log.txt 2>&1
```

............E...........EE......E...........EE...E
======================================================================
ERROR: testCLI (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testCLI
Traceback (most recent call last):
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/jraysajulga/Github/metaquantome-master/tests/testCLI.py", line 2, in <module>
    from tests.testutils import testfile, TTEST_SINFO
ImportError: No module named 'tests.testutils'


======================================================================
ERROR: testFilter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testFilter
Traceback (most recent call last):
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/jraysajulga/Github/metaquantome-master/tests/testFilter.py", line 3, in <module>
    from tests.testutils import testfile, TTEST_SINFO
ImportError: No module named 'tests.testutils'


======================================================================
ERROR: testFunTaxInteraction (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testFunTaxInteraction
Traceback (most recent call last):
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/jraysajulga/Github/metaquantome-master/tests/testFunTaxInteraction.py", line 5, in <module>
    from tests.testutils import testfile
ImportError: No module named 'tests.testutils'


======================================================================
ERROR: testFunction (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testFunction
Traceback (most recent call last):
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/jraysajulga/Github/metaquantome-master/tests/testFunction.py", line 9, in <module>
    from tests.testutils import testfile, TTEST_SINFO
ImportError: No module named 'tests.testutils'


======================================================================
ERROR: testIO (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testIO
Traceback (most recent call last):
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/jraysajulga/Github/metaquantome-master/tests/testIO.py", line 7, in <module>
    from tests.testutils import testfile, TTEST_SINFO
ImportError: No module named 'tests.testutils'


======================================================================
ERROR: testNCBITaxonomyDb (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testNCBITaxonomyDb
Traceback (most recent call last):
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/jraysajulga/Github/metaquantome-master/tests/testNCBITaxonomyDb.py", line 5, in <module>
    from tests.testutils import testfile
ImportError: No module named 'tests.testutils'


======================================================================
ERROR: testTaxonomyAnalysis (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testTaxonomyAnalysis
Traceback (most recent call last):
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/jraysajulga/miniconda3/envs/metaquantome/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/jraysajulga/Github/metaquantome-master/tests/testTaxonomyAnalysis.py", line 4, in <module>
    from tests.testutils import testfile, TTEST_SINFO
ImportError: No module named 'tests.testutils'


----------------------------------------------------------------------
Ran 50 tests in 26.293s

FAILED (errors=7)
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/test/go_cache/go-basic.obo: fmt(1.2) rel(2018-10-30) 47,358 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/test/go_cache/goslim_metagenomics.obo: fmt(1.2) rel(None) 185 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/test/go_cache/go-basic.obo: fmt(1.2) rel(2018-10-30) 47,358 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/test/go_cache/goslim_metagenomics.obo: fmt(1.2) rel(None) 185 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/go/go-basic.obo: fmt(1.2) rel(2018-10-30) 47,358 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/go/go-basic.obo: fmt(1.2) rel(2018-10-30) 47,358 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/go/go-basic.obo: fmt(1.2) rel(2018-10-30) 47,358 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/tmp_go_data_dwnld/go-basic.obo: fmt(1.2) rel(2018-11-08) 47,363 GO Terms
/Users/jraysajulga/Github/metaquantome-master/metaquantome/data/tmp_go_data_dwnld/goslim_metagenomics.obo: fmt(1.2) rel(None) 185 GO Terms

```

**Comment by caleb-easterly** [comment]
Resolved by d93bc1c770e1319e5ce01b4b9fe26d470b45ef8f
