### ISSUE TITLE
Trouble with path on command line

### ISSUE THREAD

**Issue by caleb-easterly** [caleb-easterly/metaquantome#4]
I moved `cli.py` into `metaquantome/metaquantome` to help with packaging (commit 0dfdc3c67c83f21bac59f3852c9cdd56d175977e) , but that causes problems on the command line. This is from the Travis log testing `testCLI.py`:

```
> python3 metaquantome/cli.py expand -m f --pep_colname_int peptide --pep_colname_func peptide --outfile /home/travis/build/galaxyproteomics/metaquantome/metaquantome/data/test/cli_mult_out.tab -i metaquantome/data/test/int_ttest.tab --func_file metaquantome/data/test/multiple_func.tab  --func_colname cog --ontology cog  --samps '{"s1": ["int1", "int2", "int3"], "s2": ["int4", "int5", "int6"]}' 
Traceback (most recent call last):
  File "metaquantome/cli.py", line 5, in <module>
    from metaquantome.analysis.expand import expand
ImportError: No module named 'metaquantome'
FTraceback (most recent call last):
  File "metaquantome/cli.py", line 5, in <module>
    from metaquantome.analysis.expand import expand
ImportError: No module named 'metaquantome'
```

**Comment by caleb-easterly** [comment]
Got it working! Not sure if this is the best way, but I added the parent directory (i.e., parent metaquantome) to the path from inside `cli.py` (see dd48d3b38cd1bdc35f148e27c514f0dbeface6d3) 

I also re-added setup.py and made sure to include the viz.R file separately.
